// Generated from the game server's operation output schemas. Do not edit by hand.
/** The `data` keys each command's response can carry, by command name. */
export const responseDataKeys: Record<string, readonly string[]> = {
  monologue: ['monologue'],
  encounters: ['encounters'],
  tactics: ['tactics'],
  'tactics-set': ['validation', 'tactics'],
  'tactics-check': ['validation'],
  fight: ['activity', 'status', 'last_result', 'position', 'scenery'],
  report: ['combat_report'],
  rest: ['activity', 'status', 'last_result', 'position', 'scenery'],
  inn: ['activity', 'status', 'last_result', 'position', 'scenery'],
  use: ['status', 'used_item'],
  'change-job': ['capacity', 'status', 'combat_stats'],
  'lost-items': ['lost_items'],
  recover: ['capacity', 'status'],
  'quest-board': ['quest_board', 'quest_board_budget'],
  quests: ['quests'],
  'quest-accept': ['quest', 'status', 'reputation_change'],
  'quest-claim': ['quest', 'status', 'reputation_change'],
  'quest-discard': ['quest', 'status', 'reputation_change'],
  journal: ['journal', 'journals'],
  'journal-write': ['journal'],
  end: [
    'journal',
    'session_ended',
    'activity',
    'last_result',
    'capacity',
    'status',
  ],
  plan: ['plan'],
  'plan-set': ['plan_saved'],
  chat: ['chat'],
  news: ['news'],
  'news-article': ['news_article'],
  'chat-send': ['chat'],
  dm: ['direct_messages'],
  'dm-conversations': ['direct_conversations'],
  'dm-send': ['direct_messages'],
  board: ['board_threads'],
  'board-thread': ['board_thread'],
  'board-create': ['board_thread', 'board_quota'],
  'board-reply': ['board_post', 'board_quota'],
  market: ['market'],
  'my-market': ['my_market'],
  'market-sell': ['order_placement', 'status'],
  'market-buy': ['order_placement', 'status'],
  'market-order-cancel': ['market_cancellation', 'status'],
  'market-order-claim': ['market_claim', 'status'],
  'market-list': ['listing_created', 'status'],
  'market-purchase': ['listing_purchase', 'status'],
  'market-listing-cancel': ['market_cancellation', 'status'],
  'market-listing-claim': ['market_claim', 'status'],
  hello: [
    'character',
    'inventory',
    'capacity',
    'activity',
    'rest_estimate',
    'combat_stats',
    'journal',
    'plan',
    'quests',
    'scenery',
    'last_result',
    'changelog',
    'announcement',
  ],
  characters: ['characters'],
  'search-characters': ['search_results'],
  'resolve-character': ['characters'],
  options: ['options'],
  character: [
    'character',
    'inventory',
    'capacity',
    'activity',
    'rest_estimate',
    'combat_stats',
  ],
  create: ['created'],
  profile: ['profile_saved'],
  map: ['map', 'position'],
  look: ['look'],
  route: ['route'],
  activity: ['activity', 'last_result', 'position', 'scenery', 'status'],
  travel: ['activity', 'status', 'last_result', 'position', 'scenery'],
  carriage: ['activity', 'status', 'last_result', 'position', 'scenery'],
  gather: [
    'activity',
    'capacity',
    'status',
    'last_result',
    'position',
    'scenery',
  ],
  recipes: ['recipes'],
  items: ['items'],
  craft: [
    'activity',
    'capacity',
    'status',
    'last_result',
    'position',
    'scenery',
  ],
  stop: ['activity', 'last_result', 'capacity', 'status'],
  shop: ['shop'],
  buy: ['purchase', 'status'],
  equip: ['capacity', 'status', 'combat_stats'],
  unequip: ['capacity', 'status', 'combat_stats'],
  repair: ['capacity', 'status', 'repair'],
  discard: ['capacity', 'status'],
  storage: ['storage'],
  'search-storage': ['storage_search'],
  deposit: ['capacity', 'transfer', 'status'],
  withdraw: ['capacity', 'transfer', 'status'],
};
